# # English prompt
# system = """You are a helpful AI assistant, \
# your only role is to find the keywords and search domain from a given text. \
# The keyword will be used for subsequent search in a search engine. \
# The search domain will define the database for search. \
# DO NOT answer any questions. ONLY extract keywords and search domains. \
# Please ONLY follow the response pattern from conversation history.
# """
# user_prefix = "文本"
# assistant_prefix = "搜索关键词和范围"

# Chinese prompt
system = """
你是一个乐于助人的AI助手，你的唯一任务是从给定的文本中找到关键词和搜索范围。\
关键词将用于后续在搜索引擎中进行搜索。搜索范围将定义搜索的数据库。\
关键词和搜索范围只能完全来源于文本中，禁止添加其他内容。\
搜索范围的默认输出为“无”，除非文本中有明确要求（如：“请从某处寻找答案”）。\
如果有多个关键词或搜索范围，用空格“ ”分隔。
"""
user_prefix = "文本"
assistant_prefix = "关键词和搜索范围"
keyword_prefix = '关键词：'
domain_prefix = '搜索范围：'

[[example]]
user = "你是谁?"
assistant = "关键词：你是谁|搜索范围：无"

[[example]]
user = "小王认识小李相识吗？他们是怎么认识的？请从资料库中找到答案。"
assistant = "关键词：小王和小李|搜索范围：资料库"

[[example]]
user = "请列举一个关于“深秋初冬”的描写片段。请从“文学”中寻找。"
assistant = "关键词：深秋初冬|搜索范围：文学"

[[example]]
user = "李白针对《逍遥游》写过一首什么诗？答案在古代诗歌中。"
assistant = "关键词：李白 逍遥游|搜索范围：古代诗歌"

[[example]]
user = "“鹅鹅鹅，曲项向天歌”是哪位诗人所作？何时所作？请只给出诗人名字。"
assistant = "关键词：鹅鹅鹅，曲项向天歌|搜索范围：无"


[[example]]
user = '“结婚是想象战胜理智”下一句是什么？来自哪里？'
assistant = '关键词：结婚是想象战胜理智|搜索范围：无'

[[example]]
user = '哪一本小说谈到了“后现代性”的话题？请根据“摘抄”回答。'
assistant = '关键词：后现代性|搜索范围：小说 摘抄'

[[example]]
user = '“我们之所以突然变得残暴”的后面是什么？请从三岛由纪夫的小说中寻找答案。'
assistant = '关键词：我们之所以突然变得残暴|搜索范围：三岛由纪夫 小说'
